### ISSUE TITLE
Rust: build fails on SIGILL non-deterministically

### ISSUE THREAD

**Issue by chebbyChefNEQ** [lancedb/lance#1010]
Example failed run: https://github.com/lancedb/lance/actions/runs/5352836458/attempts/2

Re-run usually fixes the build. Possible cause by `target-cpu` specification.

Assuming test ordering is deterministic in cargo.  the failing test is `arrow::linalg::matrix::tests::test_dot_on_transposed_mat`

**Comment by eddyxu** [comment]
Looks like GHA have a few generations of CPUs to run on.

**Comment by changhiskhan** [comment]
let's try using larger runners first: https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners

**Comment by changhiskhan** [comment]
Looks like it's solved with larger runners. Can reopen if this recurs
