### ISSUE TITLE
Regression in writing BooleanArray with nulls

### ISSUE THREAD

**Issue by changhiskhan** [lancedb/lance#1027]
First reported by @dnsco 

When writing an Arrow batch to Lance, encountered panic on https://github.com/lancedb/lance/blob/main/rust/src/encodings/plain.rs#L93

Not verified but it appears to be calling unwrap on a potential None value if the BooleanArray is nullable.

This did not occurs in previous versions (this particular piece of code was modified with the unwrap recently so the timing checks out).

**Comment by dnsco** [comment]
Our test passes in 0.4.21 but fails in 0.5.1
