### ISSUE TITLE
Support "true" predicate in deletion

### ISSUE THREAD

**Issue by wjones127** [lancedb/lance#1074]
This allows clearing the table to an empty state.

Right now this fails during the deletion scan, since we are scanning no columns. We should instead short circuit and remove all fragments if the filter is always true or false.

**Comment by Weijun-H** [comment]
Could I try to take this ticket?

**Comment by wjones127** [comment]
@Weijun-H Sure, please feel free to open a PR.

**Comment by wjones127** [comment]
Completed in #1515
