### ISSUE TITLE
[Python] tf.data support

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lance#1081]
- [x] Convert a dataset to `tf.data.Dataset`
- [x] Auto infer schema from projection
- [x] Filter push down
- [x] Shuffle over the fragments.
- [x] Documents

**Comment by wjones127** [comment]
Does this mean implementing a TensorFlow Dataset on top of Lance or a Lance query result?

**Comment by eddyxu** [comment]
Yes, exactly.
