### ISSUE TITLE
Support SerDe Fragment metadata

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lance#1102]
To allow passing Fragment metadata across machines, i.e., in distributed writers, we need to be able to serialize enough data for Fragments. So that during commit, we could gather fragments written distributedly.

**Comment by wjones127** [comment]
We basically need all the information that will be contained by the proposed external manifest schema:

https://github.com/lancedb/lance/blob/53defbe526e68a9f54bc1525202e95f70ae136b1/docs/format.rst?plain=1#L60-L93

As JSON, that looks something like:

```json
{
  "id": 42,
  "data_files": [
    {
      "path": "some_path.lance",
      "fields": [0, 1, 2]
    }
  ],
  "deletion_file": {
    "file_type": "bitmap",
    "read_version": 28,
    "id": 53224
  },
  "num_rows": 100000,
  "num_deletions": 5000,
  "stats": "<encoded record batch>"
}
```

I think the stats might be easiest to keep as a 1 row record batch, unless we really want to create a special message for it.
