### ISSUE TITLE
Add function to delete dataset versions

### ISSUE THREAD

**Issue by wjones127** [lancedb/lance#1117]
Right now we keep all versions of a dataset, but to save disk space, we'd like to remove older versions.

The API might allow removing a specific version or all versions before one.

```python
dataset.delete_versions(1)
dataset.delete_versions(1, 3, 4)
dataset.delete_versions(before=7)
```

To perform this operation, we first need to crawl the metadata for files present in existing versions. This includes both data files, deletion files, and index files.

Then for each version to be deleted, determine which files aren't part of the existing file set. Delete those objects and the corresponding manifest file. Use [ObjectStore::delete_stream()](https://docs.rs/object_store/0.6.1/object_store/trait.ObjectStore.html#method.delete_stream) for maximum efficiency.

For operations like this, we'd like to provide the option for the user to distribute the operation. So there could be a single node implementation (configurable to use one or multiple threads) and a multi-node implementation, which returns a vector of tasks. See implementation of file compaction for inspiration: https://github.com/lancedb/lance/pull/1095

**Comment by eddyxu** [comment]
Semantic-wise,  how is this different to a `VACUUM` operation?

**Comment by wjones127** [comment]
We could also call it vacuum.

This is designed differently than Delta Lake in the sense that it won't keep around versions referencing deleted files. Right now Delta Lake deleted data files in older versions, but has a separate deletion process for the log files. So it's possible to attempt to load an old version of a table and it will return not found for the data files. IMO that's a suboptimal user experience, so I wanted to make sure our API deletes the manifest along with the orphaned data files at the same time. And I think an API that says `delete_versions()` more clearly states that you are deleting old versions of tables.

What do you think?

**Comment by wjones127** [comment]
We could also have an api like:

```python
dataset.delete_versions(older_than=timedelta(days=7))
```

Which might be a more common calling pattern.

**Comment by wjones127** [comment]
@westonpace should this be considered closed now that we have a ticket for Python?

**Comment by westonpace** [comment]
Yes, I think so.

**Comment by prrao87** [comment]
Hi, I'd like to understand how this functionality is exposed to LanceDB? I'm adding data to a LanceDB table via `tbl.add(data, mode='append'`) and it's not clear from the [add method's code](https://github.com/lancedb/lancedb/blob/343e274ea5713b0172b420ea0566b1c995a0d795/python/lancedb/table.py#L523) that the older versions of the manifests are cleaned up this way.

Could you please clarify if deleting old versions beyond a certain threshold is possible in LanceDB at present?
