### ISSUE TITLE
Write chunked batch at the Fragment level

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lance#1144]
To facilitate the distributed writers, we should have the fine-granularity write control at the Fragment level

Right now, the chunked stream of RecordBatch is done at the global level 

https://github.com/lancedb/lancedb/blob/f35f8e451fb6b8f83ca4bad68aefb22c1341eece/node/src/arrow.ts#L36, which only works if we have one single writer.

**Comment by wjones127** [comment]
This seems very doable.

Is that link related?
