### ISSUE TITLE
[Python][Rust] Design a Image extension type

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lance#1199]
# Problem Statement

To improve data lake for multi-model data, we could provide a Image type as arrow extension type for users to easily manipulate data.

Requirements:

* Be able to store image in a form that easy to inspect, store, integration with the existing image / computer vision tooling
* Be able to load into pytorch and tensorflow as tensors transparently.
* Strong typed that we can apply special kernel during projection, and filtering.

Previous related work:

We have done similar work in the framework of Spark Extension type and Parquet , and PyTorch

* https://github.com/eto-ai/rikai/blob/main/python/rikai/types/vision.py
* Pytorch: https://github.com/eto-ai/rikai/blob/main/python/rikai/pytorch/transforms.py

**Comment by rok** [comment]
Resolved with https://github.com/lancedb/lance/pull/1272. Video types will be tracked in #1384.
