### ISSUE TITLE
Lazily import optional pylance dependencies

### ISSUE THREAD

**Issue by wjones127** [lancedb/lance#1217]
Right now if Pandas is installed, we will import it. This adds at least 500ms to the time to execute `import lance` on my machine. Not as bad, but similar story with numpy.

In total, a program that just does `import lance` takes 3.8s on my machine.

This could be considered part of the cold start time for a serverless function using pylance.

**Comment by rishabhRsinghvi** [comment]
Hello @wjones127, I would like to take this issue. Thank you.

**Comment by Preetraj2002** [comment]
Hi @rishabhRsinghvi have you started to work on this issue. If not can we both work on this together.

**Comment by rishabhRsinghvi** [comment]
Hi @Preetraj2002  let's work on it together I completely forgot it due to rotki and my exams.

**Comment by rishabhRsinghvi** [comment]
@wjones127 Is this basically what I have to do?

for ex. for lancedb,
import importlib
def lazy_import_lancedb():
    try:
        return importlib.import_module("lancedb")
    except ImportError:
        return None
lancedb = lazy_import_lancedb()
if lancedb:
    # You can now use Pandas safely
else:
    print("lancedb is not installed.")
    
for ex. for Pandas, 
import importlib
def lazy_import_pandas():
    try:
        return importlib.import_module("pandas")
    except ImportError:
        return None
pandas = lazy_import_pandas()
if pandas:
    # You can now use Pandas safely
    df = pandas.DataFrame(...)
else:
    print("Pandas is not installed.")

for ex. for numpy, 
import importlib
def lazy_import_numpy():
    try:
        # Attempt to import "numpy"
        return importlib.import_module("numpy")
    except ImportError:
        # Handle the case where "numpy" is not installed
        return None
#later, when you need "numpy":
numpy = lazy_import_numpy()
if numpy:
    # You can now use "numpy" safely
    # Example usage: numpy.array(...)
else:
    print("numpy is not installed.")


just tell me where do i have to modify these changes, i.e. which files, is it all the files where pylance dependencies have been imported or just some places?

**Comment by rishabhRsinghvi** [comment]
@wjones127 and do you guys have discord for lancedb wherein we can discuss stuffs related to it, because it's going to be a lot more from here..

**Comment by wjones127** [comment]
Yes, we have a discord here: https://discord.gg/zMM32dvNtd

**Comment by rishabhRsinghvi** [comment]
@wjones127 hey, and can you tell me do I have to lazy import all pylance dependencies in each and every file pylance dependencies mean pandas, numpy, etc right if I am not wrong..

**Comment by rishabhRsinghvi** [comment]
@wjones127 
This is all I have to do?
https://www.tutorialspoint.com/lazy-import-in-python

**Comment by rishabhRsinghvi** [comment]
@wjones127 ok now it makes sense a lot, if i find any issue I will discuss here in comments itself.

**Comment by wjones127** [comment]
I'd like for us to handle all instances of those imports.

**Comment by rishabhRsinghvi** [comment]
so this is the following code i will add to dependencies.py

# dependencies.py

try:
    from pandas import DataFrame as _PandasDataFrame
    _PANDAS_AVAILABLE = True
except ImportError:
    _PANDAS_AVAILABLE = False

try:
    import numpy as _np
    _NUMPY_AVAILABLE = True
except ImportError:
    _NUMPY_AVAILABLE = False

try:
    from polars import DataFrame as _PolarsDataFrame
    _POLARS_AVAILABLE = True
except ImportError:
    _POLARS_AVAILABLE = False

def _check_for_pandas(obj, *, check_type=True):
    return _PANDAS_AVAILABLE and (
        check_type or isinstance(obj, _PandasDataFrame)
    )

def _check_for_numpy(obj, *, check_type=True):
    return _NUMPY_AVAILABLE and (
        check_type or isinstance(obj, _np.ndarray)
    )

def _check_for_polars(obj, *, check_type=True):
    return _POLARS_AVAILABLE and (
        check_type or isinstance(obj, _PolarsDataFrame)
    )
    

In original code that performs type checks, one can import and use these functions:

from .dependencies import _check_for_pandas, _check_for_polars, _check_for_numpy

if _check_for_pandas(data_obj):
    # Handle Pandas DataFrame
elif _check_for_polars(data_obj):
    # Handle Polars DataFrame
elif _check_for_numpy(data_obj):
    # Handle NumPy ndarray
else:
    # Other cases or error handling

**Comment by rishabhRsinghvi** [comment]
so what it seems to me is that

This code 1733-1753 in dependencies.py is specific to the project's requirements for handling different types of input data objects. It's designed to check the type of data_obj and perform appropriate actions based on its type. The provided type checks and actions should be part of the project's logic, and we can integrate the lazy import approach for dependencies as discussed above while keeping these type checks intact. The lazy imports will help reduce unnecessary imports of dependencies like Pandas, Numpy, or Polars when those checks are performed.

**Comment by rishabhRsinghvi** [comment]
@wjones127 please reply, I am pushing this.

**Comment by wjones127** [comment]
> ```
> try:
> from pandas import DataFrame as _PandasDataFrame
> ```

This imports Pandas, which still causes the delay. Remember, the goal of this issue is to make importing lance faster, by delaying imports of dependencies until the moment they are needed.

Whenever trying to improve performance, it's a good idea to measure your improvement to see if it actually helps. Here, you can use the command:

```python
python -X importtime -c 'import lance'
```

(There is also [a tool called Tuna which shows how to visualize the results in it's readme](https://github.com/nschloe/tuna).)

**Comment by rishabhRsinghvi** [comment]
Ok @wjones127 now I get it, we don't have to import dependencies other than lance at all unless it is required!

**Comment by rishabhRsinghvi** [comment]
@wjones127 I tried running the above command, specifically "python -X importtime measure_import.py > import_time.log", it doesn't work!

**Comment by wjones127** [comment]
@rishabhRsinghvi I cannot help you resolve an error if you don't at least tell me exactly what the error was :) Also what was inside of `measure_import.py`?

**Comment by rishabhRsinghvi** [comment]
@wjones127 the error says that no file called measure_import exist, whereas I have added a file named measure_import in the repo which only has 
"Import Lance" run into.

**Comment by rishabhRsinghvi** [comment]
@wjones127 the error says that no file called measure_import exist, whereas I have added a file named measure_import in the repo which only has 
"Import Lance" run into.

**Comment by rishabhRsinghvi** [comment]
@wjones127 before that I tried running simply the command you gave in terminal of root directory of lance repo, it still gave similar error, saying no such dependency was imported.

**Comment by wjones127** [comment]
You need to run in the Python directory, not the root directory of the repo. Also make sure you have run `maturin develop` to build the Python module. You can read more in DEVELOPMENT.md

**Comment by rishabhRsinghvi** [comment]
from typing import Any, Hashable, cast

_NUMPY_AVAILABLE = True
_PANDAS_AVAILABLE = True
_POLARS_AVAILABLE = True

# Add this function to check for Numpy
def _check_for_numpy(obj: Any, *, check_type: bool = True) -> bool:
    return _NUMPY_AVAILABLE and _might_be(
        cast(Hashable, type(obj) if check_type else obj), "numpy"
    )

# Add this function to check for Pandas
def _check_for_pandas(obj: Any, *, check_type: bool = True) -> bool:
    return _PANDAS_AVAILABLE and _might_be(
        cast(Hashable, type(obj) if check_type else obj), "pandas"
    )

# Add this function to check for Polars
def _check_for_polars(obj: Any, *, check_type: bool = True) -> bool:
    return _POLARS_AVAILABLE and _might_be(
        cast(Hashable, type(obj) if check_type else obj), "polars"
    )

**Comment by rishabhRsinghvi** [comment]
I think we can just use the same implementation used in polars, am i going correct?
