### ISSUE TITLE
fix linux arm wheel release

### ISSUE THREAD

**Issue by chebbyChefNEQ** [lancedb/lance#1286]
arm wheel release is failing since 0.7.4 because the builder is getting OOM killed. Maybe trim debug symbols would help?

**Comment by wjones127** [comment]
Can we use a larger runner just for release? I recall the arm instances have very little memory.

**Comment by chebbyChefNEQ** [comment]
https://github.com/rust-lang/cargo/issues/10583

probably the same cause. we should try setting [net.git-fetch-with-cli = true](https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli)

**Comment by wjones127** [comment]
hmm. Could we try sparse-registry? https://blog.rust-lang.org/2022/06/22/sparse-registry-testing.html

https://github.com/rust-lang/cargo/issues/9069#issuecomment-1479945166
