### ISSUE TITLE
Incorrect number of rows returned from vector search when `use_index=False`

### ISSUE THREAD

**Issue by changhiskhan** [lancedb/lance#1321]
first reported by nate harada on discord:

<img width="1177" alt="image" src="https://github.com/lancedb/lance/assets/759245/47d647cb-033a-4f4f-a7d7-8a607e3ed794">

I reproduced locally with a different dataset

<img width="1010" alt="image" src="https://github.com/lancedb/lance/assets/759245/ce2a34ef-c8af-4458-85f2-fc0830d58295">

**Comment by wjones127** [comment]
I think the issue is simply that `k` defaults to 10 if not supplied:

https://github.com/lancedb/lance/blob/c7151987cfb15952d431930166e12c01e382e891/python/src/dataset.rs#L329-L332

We can make it default to `limit` if that's provided instead, if that's less confusing.
