### ISSUE TITLE
A flat KNN is run even if the refine factor == 1

### ISSUE THREAD

**Issue by westonpace** [lancedb/lance#1385]
You can set the refine factor to None and it will skip the flat KNN step.  However, I also assumed that setting the refine factor to 1 would skip the flat KNN step but this is not true.  Perhaps this intentional (refine_factor=1 means "don't take additional rows but do run a flat KNN step to make sure the sorting stays the same when the vectors have been fully inflated") but it isn't documented.  In fact, refine_factor isn't documented much in the API docs at all.

**Comment by changhiskhan** [comment]
This is intentional but yeah it should be better documented. Let's keep this open. Basically there are use cases where you really care about the top result when you fetch 10 and this improves recall@1 with limit 10 let's say
