### ISSUE TITLE
arm build failing

### ISSUE THREAD

**Issue by wjones127** [lancedb/lance#1461]
Failure: https://github.com/lancedb/lance/actions/runs/6631701633/job/18015778470

Looks like same issue as here:
https://github.com/briansmith/ring/issues/1728

**Comment by chebbyChefNEQ** [comment]
I think amazon linux 2 compatible with on 2_26, does that work?

**Comment by chebbyChefNEQ** [comment]
> but was that just for x86?
yeah, if we want to upgrade manylinux for ARM only I think it's fine

**Comment by wjones127** [comment]
Nevermind there was actually a workaround in the upstream thread 💯
