### ISSUE TITLE
bug: do not require the fixed-size-list `value_field` to be named "item"

### ISSUE THREAD

**Issue by judahrand** [lancedb/lance#1482]
DuckDB seems to write the `value_field` of list as `"l"` rather than what Arrow expects (`"item"`) or Parquet uses (`"element"`). Why, I cannot guess. However, Lance doesn't seem to handle this:

```python
import lance
import pyarrow
import duckdb


my_table = pyarrow.Table.from_pydict({
    'id': [1, 1, 2, 2],
    'data': [1, 2, 3, 4],
})

grouped = duckdb.query('''
    select
        id,
        list(data)
    from my_table
    group by id
''').to_arrow_table()

lance_ds = lance.write_dataset(grouped, 'test_lance')
lance_ds.to_table()
```

results in

```
ArrowInvalid: C Data interface error: Io error: Execution error: External error: Execution error: LanceError(Arrow): Invalid argument error: column types must match schema types, expected List(Field { name: "l", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }) but found List(Field { name: "item", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }) at column index 1
```

**Comment by eddyxu** [comment]
Should we upgrade duckdb version as well in the same work?

**Comment by westonpace** [comment]
I've renamed the issue because this can happen even when you aren't using duckdb.

**Comment by wjones127** [comment]
FYI I'm working on how we represent schemas in Lance, and I think I'm inclined to not write out list field names. It could default to `"item"` on read, but I think we should make it so we aren't sensitive to these inner field names in most places, if possible.
