### ISSUE TITLE
Use datafusion kernel to do IVF partition shuffling

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lance#1483]
Most of the time, `num_partitions` >> `num_rows_per_partition`. For example, you might have 10,000 partitions each with 256 rows. Thus it's not practical to buffer the partition data in memory.

Instead, we can do the partitioning by performing a disk-spilling sort. This kind of sort is already supported by DataFusion, so we can implement it with the query plan:

1. Projection: assign partition id, replace vector column with PQ codes. (see: [transform.rs](https://github.com/lancedb/lance/blob/main/rust/lance-index/src/vector/pq/transform.rs), [residual.rs](https://github.com/lancedb/lance/blob/main/rust/lance-index/src/vector/residual.rs))
2. Sort: sort by partition id, making sure to set a memory limit so we spill to disk
3. Group By: group by partition id (we'll likely do the group by ourselves, since I don't think DF can optimize grouping sorted data)
4. For each group, write partition to index.

**Comment by wjones127** [comment]
Blocked by https://github.com/lancedb/lance/issues/1520
