### ISSUE TITLE
Proposal: enforce patch version bumps don't have breaking changes

### ISSUE THREAD

**Issue by wjones127** [lancedb/lance#1492]
Right now, we don't promise API stability while we are on 0.X releases. This means that downstream packages (such as LanceDB) have to pin to an exact version, or else risk breaking changes. Because of this pinning, each time we release a new version, we have to also make a PR incrementing the pinned pylance version in LanceDB.

Proposal: we could require that if there is a breaking change, there should be a **minor** version bump and not a **patch** version bump. To help identify breaking changes, we should make sure we have a tag in PR titles per [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). (For example, `feat(api!): change API for XXX`.) Then downstream packages could pin to `~=0.X.0` and automatically receive compatible updates.

This enforcement is compatible with [semantic versioning](https://semver.org/).

**Comment by wjones127** [comment]
The flaw here is that for Nodejs LanceDB, it's statically linked to a particular Lance version, so it needs to be bumped / re-released.

**Comment by changhiskhan** [comment]
We should have a docs / release / blogging / tech debt sprint soon

**Comment by westonpace** [comment]
@wjones127 is this done now?

**Comment by wjones127** [comment]
Yes, this was implemented in #2324. Thanks for reminding me :)
