### ISSUE TITLE
allow more configuration options for ObjectStore

### ISSUE THREAD

**Issue by universalmind303** [lancedb/lance#1542]
Currently there are little options available for creating an `ObjectStore`. Especially if you want to customize the underlying `OSObjectStore`. 

The use case I am facing is using a google cloud object store. The current implementation will **always** read it from the env. I'd like to be able to either pass in the `OSObjectStore` directly, or allow for more customization. 

The [DeltaTableBuilder](https://github.com/delta-io/delta-rs/blob/main/crates/deltalake-core/src/table/builder.rs#L146) is a good example. It provides many utility options for customizing the underlying object store.

**Comment by wjones127** [comment]
Related: #1541

**Comment by universalmind303** [comment]
@wjones127 I'd like to work on this one. feel free to assign to me!
