### ISSUE TITLE
If there is a vector search then the output always contains the vector column even if not included in project

### ISSUE THREAD

**Issue by westonpace** [lancedb/lance#1565]
We need to load the vector column to do the vector search so this isn't really a performance concern.  However, as a user, if I specifically list the columns I want, then I probably don't expect there to be extra columns (except _distance).

I've opened this as an issue as I'm not sure if this is expected behavior (in which case we should document it) or not (in which case we should fix it).

I do think there will be situations where users will want the vector search but not the vector column.  For example, maybe the vector column is an image embedding and the data they really want is the image itself or a URL for the image.

**Comment by wjones127** [comment]
Duplicate of https://github.com/lancedb/lance/issues/1490 ?

**Comment by westonpace** [comment]
Yep.

Duplicate of #1490
