### ISSUE TITLE
Scalar index performance for `x NOT IN (0)` is considerably worse than `x != 0`

### ISSUE THREAD

**Issue by westonpace** [lancedb/lance#1641]
Also, if there are multiple values, (e.g. `x NOT IN (0, 1)`) then it appears that `x != 0 && x != 1` is still faster.  It's possible there is a cutoff somewhere (e.g. I believe `NOT IN` is using a hashmap for the value set which is probably faster once the value set is sufficiently large) or it is possible there is a bug.  Either way we should be able to ensure the scalar index performs well with small value sets.

**Comment by wjones127** [comment]
Reminds me of: https://github.com/apache/arrow-datafusion/blob/4195f2f367648f9c2ed990f2948248e53f503f9b/datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs#L497-L512
