### ISSUE TITLE
blog post: statistics and scanning

### ISSUE THREAD

**Issue by wjones127** [lancedb/lance#1691]
Write a blog post covering:

* Addition of new statistics
   * How we made them more like page index than row group stats
* How we implemented it
  * Use of expression simplification + late materialization
* Role of DataFusion's expression libraries
* Relation to scalar indices
* Where they are integrated, and where they are not
  * Integrated: scans, deletion
  * TODO: scans with scalar index, prefilter

**Comment by changhiskhan** [comment]
completed. thanks!
