### ISSUE TITLE
feat: consider build multi-cpu binary for intel linux build

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lance#1733]
# Problem Statement

Current, we build lance linux wheel against to intel `haswell` cpu, as that's the oldest CPUs used among the cloud vendors (AWS / GCP / Azure). However, this cpu target generates slow code path.

Use skylake / icelake as target-cpu can deliver significant  better performance. 

Consider 
* https://www.reddit.com/r/rust/comments/18iqr0r/building_one_binary_that_targets_multiple_cpus/?share_id=3ad1TxkBj2IeqKOJbLAMZ&utm_content=1&utm_medium=ios_app&utm_name=ioscss&utm_source=share&utm_term=1
* https://github.com/ronnychevalier/cargo-multivers
*

**Comment by wjones127** [comment]
Is the idea here to use [https://crates.io/crates/multiversion](https://crates.io/crates/multiversion) for runtime dispatch to SIMD kernels?

**Comment by eddyxu** [comment]
Yes, exactly.

**Comment by eddyxu** [comment]
Gonna give up this effort.

`x86_64/haswell` and `x86_64/skylake` targets are not compilable on the stable rustc. which makes our default build more aggressive than `multiversions` already.
