### ISSUE TITLE
Dataframe: access to dotted field names like SQL

### ISSUE THREAD

**Issue by pchalasani** [lancedb/lance#1738]
In the `where` clause, the SQL query can access arbitrarily nested fields, but this is not possible with the dataframe, e.g. I want to be able to do:

```
df = tbl.search().to_pandas()
```
and be able to see all nested fields of the schema as top-level columns in `df`.
Among other things this would enable `pandas` queries like `df.query(...)`

**Comment by wjones127** [comment]
Hmm if I could I would add a `flatten` parameter to `to_pandas()`, but we don't control that method (it's in PyArrow).

Other DataFrames do have decent support for nested columns, such as Polars. So I don't think flattening in general is what we want.

Perhaps we can provide a helpful snippet to teach them how to unflatten a column? IIRC it's just something like:

```python
df.assign(nested = lambda df: [x['key'] for x in df['struct']])
```

**Comment by changhiskhan** [comment]
@pchalasani i think we can do this in LanceDB repo instead of the format level (please see the referencing PR)

**Comment by pchalasani** [comment]
Nice, thanks, I seem to be conflating the two repos in my mind 😀

**Comment by wjones127** [comment]
For future reference for Lance users, you can write:

```python
dataset.to_table(...).flatten().to_pandas()
```

If you have multiple levels of nested fields, you may need to call `flatten()` multiple times.

Maybe I can make this a tip in the user guide?

**Comment by pchalasani** [comment]
Yes an example in the user guide would help, thanks
