### ISSUE TITLE
shuffle progress log resets count on new partition

### ISSUE THREAD

**Issue by chebbyChefNEQ** [lancedb/lance#1745]
the count here: https://github.com/lancedb/lance/blob/main/rust/lance-index/src/vector/ivf/shuffler.rs#L167-L170

should be `partition_id`: `idx` / `shuffle_partition_size`

**Comment by seankhatiri** [comment]
Hi there, 
I'm new to lance,
you mean sth like this?

partition_id = idx / partition_size;
            if partition_id % 100 == 0 {
                info!("Shuffle Progress {}/{}", partition_id, total_batch);
            }

**Comment by chebbyChefNEQ** [comment]
> https://github.com/lancedb/lance/blob/main/rust/lance-index/src/vector/ivf/shuffler.rs#L167-L170

Hi!

Yes something like that. For one, for each sub shuffle task, we don't really need to print the `total_batch`. instead, just `end - start` is good. Then, we probably want to print `task_id/total_tasks` so we know the overall progress..

**Comment by seankhatiri** [comment]
Thanks, 
I've created a pull request for the first part here: https://github.com/lancedb/lance/pull/1747#issue-2054877047

But for the second part( overall progress), would u plz elaborate on total_tasks?

I couldn't find the notion of task, therefore I guess  we consider each idx as task_id and total_batches as total_tasks?
