### ISSUE TITLE
Improve bfloat16 array interoperability with fixed size list and fixed size tensor array

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lance#1750]
Improve the following operations

- [ ] BFloat16 array to/from f16 / f32 arrays
- [ ] BFloat16 FixedSizeList / FixedSizeTensor cast to f16 / f32 FixedSizeList / FixedSizeTensor
- [ ] FixedSizeList / FixedSizeTensor from / to bf16 array directly.

**Comment by wjones127** [comment]
Fixed by #1753
