### ISSUE TITLE
Investigate approaches to handling null

### ISSUE THREAD

**Issue by westonpace** [lancedb/lance#1794]

**Comment by wjones127** [comment]
One relevant question with null handling: In Arrow, struct columns themselves can be null. In Parquet, this is a not the case. ([There's a good blog post on the Arrow blog about this](https://arrow.apache.org/blog/2022/10/08/arrow-parquet-encoding-part-2/)). What approach do we want to take this Lance? I think being Parquet like will make more sense from an IO perspective, but it means we'll want to spell out how we translate the Arrow nullability to Lance.

**Comment by westonpace** [comment]
duplicate of #1643
