### ISSUE TITLE
Cleanup and compaction are missing from API docs

### ISSUE THREAD

**Issue by westonpace** [lancedb/lance#1823]
I believe its because these methods are only on `LanceTable` (and not `Table`).  I would expect to see them here:

![image](https://github.com/lancedb/lance/assets/1696093/3890a632-e1ca-4304-a69a-78f7e3593bd4)

**Comment by wjones127** [comment]
@westonpace this is for LanceDB, not Lance, right?

**Comment by westonpace** [comment]
Yes :flushed: 

Moved to https://github.com/lancedb/lancedb/issues/819
