### ISSUE TITLE
LanceError(Schema): Does not support LargeUtf8 as dictionary value type

### ISSUE THREAD

**Issue by mkleinbort-ic** [lancedb/lance#1917]
I'm unable to write a .lance file from a polars dataframe with a Categoricals on polars String fields field.

See here:

```python
import lance
import polars as pl 

df = pl.DataFrame({'x':['Some very long text'*20]}).cast({'x':pl.Categorical})
lance.write_dataset(df, uri='test.lance')
```

Raises:

```python
ValueError: LanceError(Schema): Does not support LargeUtf8 as dictionary value type
```

**Comment by wjones127** [comment]
Thanks for reporting @mkleinbort-ic. It turns out this is a very simple fix; we just had a too narrow type check in one spot. This should be fixed in the next release.
