### ISSUE TITLE
Add `storage_options` parameter to `lance.dataset`

### ISSUE THREAD

**Issue by mkleinbort-ic** [lancedb/lance#1930]
Currently lance.dataset can read from any Azure/S3/GCP uri, provided the environment variables allow it to authenticate with the cloud provider.

However, it'd be good to allow `lance.dataset(uri, storage_options)`, where `storage_options` is a `dict` as seen here:

```python

import polars as pl

source = "s3://bucket/*.parquet"

storage_options = {
    "aws_access_key_id": "<secret>",
    "aws_secret_access_key": "<secret>",
    "aws_region": "us-east-1",
}

df = pl.scan_parquet(source, storage_options=storage_options)

```

This is important when you need to authenticate a read operation to a bucket, but you don't want to change the env variable.

**Comment by wjones127** [comment]
We already have storage option parsing in Rust: https://docs.rs/lance/0.9.13/lance/dataset/builder/struct.DatasetBuilder.html#method.with_storage_options

So this is just a matter to exposing in Python. `lance.dataset` seems like a natural place to do that 👍
