### ISSUE TITLE
Scanner tech debt

### ISSUE THREAD

**Issue by chebbyChefNEQ** [lancedb/lance#1992]
Problems:
- [ ] schema handling and planning are done separately -- we should just make the plan the source of truth of schema
- [ ] metadata is returned sometimes but not all times. Make this behavior more consistent.
- [ ] make `_rowid` and `_distance` less awkward to deal with -- so that `select([]).with_row_id()` is just `select ("_rowid")` We should reserve that column name.
- [ ] don't return `_distance` unless `select *` or `select _distance`

**Comment by eddyxu** [comment]
I think we should also consider what logic should be in lance and what should be in lancedb (as vectordb).

Lance itself as format could be more generic.

**Comment by wjones127** [comment]
We already have an issue here: https://github.com/lancedb/lance/issues/1782

I've folded these items into that issue.
