### ISSUE TITLE
Docs: Add LLM training Examples using Lance - Epic

### ISSUE THREAD

**Issue by AyushExel** [lancedb/lance#2029]
The following examples will be added to Lance under LLM training, each point is an individual page (ideally):
- [ ] Creating a dataset for LLM training (Codeparrot subset or wikitext will be nice)
- [ ] Training an LLM with a Lance dataset (along with the custom dataloader and sampler) + GPU util benchmarks

**Comment by Aryan-Deshpande** [comment]
Hey can I work on this too ?. I have a background of training/finetuning LLMs.

**Comment by tanaymeh** [comment]
> Hey can I work on this too ?. I have a background of training/finetuning LLMs. 

Hi @Aryan-Deshpande, thanks a lot for showing an interest!

Unfortunately I have already completed the code and demos and completing some backlogs before pushing the changes here.

However, we would love to see your contributions to Lance! Why don't you check out an Issue from [Lance/issues](https://github.com/lancedb/lance/issues) and open a PR for one that you are passionate about?

Cheers!
