### ISSUE TITLE
Expose `storage_options` in `write_fragments`

### ISSUE THREAD

**Issue by wjones127** [lancedb/lance#2154]
`storage_options` was added to `write_dataset` in #2131. We should do the same for `write_fragments`.

**Comment by jghoman** [comment]
👋 I'm interested in taking this ticket.

**Comment by eddyxu** [comment]
Hey, @jghoman. Curious where you are w.r.t of this fix? We would love to have this in soon, as we are facing a bug that needs this one to be the fix.

**Comment by jghoman** [comment]
Hey @eddyxu - As soon as I called dibs, my schedule exploded.  Happy to release that dib, since I'm not sure when things are going to calm down.  Will grab another startup ticket.  Thanks, Jakob
