### ISSUE TITLE
Lance / Burn sub-dependency conflict on `half` version

### ISSUE THREAD

**Issue by kafonek** [lancedb/lance#2279]
Hello Lance team. I'm going through some [burn](https://github.com/tracel-ai/burn) tutorials (Rust deep learning framework) and wanted to take a stab at data loading from a Lance table. Unfortunately there's a sub-crate dependency conflict between `burn-core` and `lance` on `half` (`burn` wants `^2.4.1`, `lance` wants `=2.3.1`). 

https://github.com/lancedb/lance/pull/1450 is where the last version bump happened. Is there a reason it's pinned exactly? Can we loosen that restriction? FWIW I did try unpinning the exact match and bumping `half` up to `2.4.1` and `cargo-test` passed, if you want that as a PR.

Thanks, appreciate all the work on the project!

**Comment by wjones127** [comment]
Yeah I frankly have no idea why it's pinned. I'm open to a PR to un pin it.
