### ISSUE TITLE
Support more encodings in format v2

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lance#2309]
- [ ] Bit packing
- [ ] Delta of Delta
- [ ] [FSST](https://www.vldb.org/pvldb/vol13/p2649-boncz.pdf)

**Comment by wjones127** [comment]
Add this to the "Beyond MVP" section of #1929

**Comment by broccoliSpicy** [comment]
can I work on the FSST compression? I might need some support

**Comment by wjones127** [comment]
You may. Could you create a dedicated issue for FSST encoding? The top-level progress of V2 format should be tracked in #1929. Link the new issue from there.

I'm going to close this to consolidate.

**Comment by broccoliSpicy** [comment]
awesome! I created issue #2415 for FSST encoding.
