### ISSUE TITLE
doc: table.proto message DataFragment documentation confusion

### ISSUE THREAD

**Issue by broccoliSpicy** [lancedb/lance#2345]
[source link](https://github.com/lancedb/lance/blob/d05a1d6fcb73c5d46ae18878698a87e6d575784a/protos/table.proto#L170)

```
 // Number of original rows in the fragment, not counting deletions. To compute
  // the current number of rows, subtract `deletion_file.num_deleted_rows` from
  // this value.
  uint64 physical_rows = 4;
```

`not counting deletions` -> counting deleted rows?

**Comment by wjones127** [comment]
Hmm. I suppose could say "Number of original rows in the fragment. This includes rows that are now marked with deletion tombstones." I think the existing second sentence is good and clarifies it though.
