### ISSUE TITLE
Concurrent create dataset gives bad error, doesn't retry

### ISSUE THREAD

**Issue by wjones127** [lancedb/lance#2403]
If a user tries to append to the same dataset concurrently, one writer will fail with a confusing internal error:

```
Internal { message: "Commit conflict", location: Location { file: "rust/lance-table/src/io/commit.rs", line: 424, column: 27 } }
```

This is because in `commit_new_dataset`, we don't retry to catch the `CommitError::CommitConflict`:

https://github.com/lancedb/lance/blob/d8da4452dae17635765c2d04d2cb3d5318149dc3/rust/lance/src/io/commit.rs#L126-L138

For comparison, in `commit_transaction()`, we have a retry loop and a nicer error message:

https://github.com/lancedb/lance/blob/d8da4452dae17635765c2d04d2cb3d5318149dc3/rust/lance/src/io/commit.rs#L486-L494

We should change this to see if the transactions are compatible and, if so, have `commit_new_dataset` load the dataset and call into `commit_transaction`.

**Comment by Patrick-Erichsen** [comment]
Quick +1 to this, I have also experienced it.
