### ISSUE TITLE
"error: Unrecognized option: 'diagnostic-width'" when first run test in visual code on mac

### ISSUE THREAD

**Issue by broccoliSpicy** [lancedb/lance#2465]
<img width="801" alt="Screenshot 2024-06-12 at 8 21 20 PM" src="https://github.com/lancedb/lance/assets/93440049/a23c6d79-d7a3-4871-91d9-2bc2c4b3a660">

steps to reproduce: 
1: install newest rust toolchain following rust website instruction
2: git clone lance
3: open lance in visual code
4: click a Run Test bottom in file editor
<img width="136" alt="Screenshot 2024-06-12 at 8 33 27 PM" src="https://github.com/lancedb/lance/assets/93440049/5bdd599e-898f-4d88-a1cd-56061a7c7db1">

my machine information:
<img width="792" alt="Screenshot 2024-06-12 at 8 39 41 PM" src="https://github.com/lancedb/lance/assets/93440049/e2e1cca5-f724-4c05-ae53-111f10c99cd3">

rust version:
```
$ rustup --version                                   
rustup 1.27.1 (54dd3d00f 2024-04-24)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.78.0 (9b00956e5 2024-04-29)`
```

lance commit:
```
f97a7cd4312b71cddfc6aebea10279a342a1241d
```

**Comment by broccoliSpicy** [comment]
I fixed this issue by first run a test in terminal, like this:
`cargo test lance_linalg::kernels::tests:test_argmax`

then the visual code test bottom works fine

**Comment by westonpace** [comment]
Thanks for the info.  Should this be closed or is there some action we can take?

**Comment by broccoliSpicy** [comment]
my guess is this is a visual code issue, or something with my local setting
