### ISSUE TITLE
Add `storage_options` to `LanceCommitter`

### ISSUE THREAD

**Issue by tonyf** [lancedb/lance#2615]
Currently, `LanceFragmentWriter` supports a `storage_options` kwarg to support specifying s3 credentials/endpoints. However, `LanceCommitter` does not have the same option and raises `TypeError: object.__init__() takes exactly one argument (the instance to initialize)` when trying to initialize it with `storage_options`.

**Comment by wjones127** [comment]
This sounds good. Seems like it's just a matter of piping `storage_options` down to `lance.LanceDataset.commit` here:

https://github.com/lancedb/lance/blob/c59996dc671c80d03bb7b9f11ccf0fcff76f5c5b/python/python/lance/ray/sink.py#L142

**Comment by BitPhinix** [comment]
Can we get a release with this fix? 🙏
