### ISSUE TITLE
lancedb version: 0.9.0  use Lance v2，the performance of the new file format is slower than the old format

### ISSUE THREAD

**Issue by wpjgit** [lancedb/lance#2629]
lancedb version: 0.9.0  use Lance v2，the performance of the new file format is slower than the old format
![image](https://github.com/user-attachments/assets/af329b27-f51f-4309-8ec9-58a863d72f7c)

**dataset**: 
parquet：https://github.com/cwida/duckdb-data/releases/download/v1.0/lineitemsf1.snappy.parquet
parquet to lance: 
lance.write_dataset(parquet, lance_path, use_legacy_format=False)
![image](https://github.com/user-attachments/assets/07fa1bec-4a56-42c1-84cd-5e112fb3ba0f)

**case**:
table = db.open_table("lineitem")
res = table.search().where("l_shipmode = 'FOB'").limit(1000000000).to_pandas()
**Latency of old format**:
![image](https://github.com/user-attachments/assets/ca21650b-ba8e-4913-96c6-de25ef17b97e)
**Latency of new format**:
![image](https://github.com/user-attachments/assets/6793c943-eea6-4c9b-9bbe-686a8d4ff5b7)

**Comment by westonpace** [comment]
Thanks for the report, this is definitely something to fix.  This query is triggering late materialization.  The v2 path is not coalescing I/O effectively here and it's translating into way too many tiny reads.
