### ISSUE TITLE
Sharded samplers don't account for dataloader's multiprocess workers

### ISSUE THREAD

**Issue by tonyf** [lancedb/lance#2713]
In a torch distributed context, there are multiple sharding dimensions— the number of dist workers and the number of dataloader multiprocess workers. When implementing a `IterableDataset` the dataset is responsible for sharding the dataset appropriately across the dist processes and dataloader processes.

The current implementation only accounts for distributed workers leading to duplicate data. The sharding samplers need to be reworked a bit because the information regarding multiprocess workers is only available when `__iter__` is called on the dataloader/dataset.

a rough solution would look like:

```
import torch.distributed as dist
import torch.utils.data


class LanceDataset(IterableDataset):
...

    @property
    def _dp_world_size(self):
        if dist.is_initialized():
            return int(dist.get_rank())
        return 0

    @property
    def _dp_rank(self):
        return get_dist_rank()

    @property
    def _mp_world_size(self):
        if (worker_info := torch.utils.data.get_worker_info()) is not None:
            return worker_info.num_workers
        return 1

    @property
    def _mp_rank(self):
        if (worker_info := torch.utils.data.get_worker_info()) is not None:
            return worker_info.id
        return 0

    @property
    def _global_world_size(self):
        return self._dp_world_size * self._mp_world_size

    @property
    def _global_rank(self):
        return self._dp_rank * self._mp_world_size + self._mp_rank

    def _get_sampler(self):
        sampler_cls = ...
        return sampler_cls(
            rank=self._global_rank,
            world_size=self._global_world_size,
            randomize=self.shuffle,
            seed=torch.default_generator.initial_seed(),
        )


    def __iter__(self):
        if self._sampler is None:
            self._sampler = self._get_sampler()
        elif self._sampler._world_size != self._global_world_size:
            self._sampler = self._get_sampler()
       
       ....
```

**Comment by tonyf** [comment]
@eddyxu I saw that you modified the dataset to get worker info from `torch.utils.data` https://github.com/lancedb/lance/blob/18fbd7a2b2453822e0a58c7a938b9c7d28917bff/python/python/lance/torch/data.py#L257

However, this only accounts for MP workers for a specified dataloader instance. It doesn't account for torch distributed workers so this dataset won't work in a torch distributed training environment.

**Comment by eddyxu** [comment]
Ah got it. Thanks for the PR !
