### ISSUE TITLE
Writing dataset with use_legacy_format=False results in a LanceDataset.data_storage_version of '0.1'

### ISSUE THREAD

**Issue by alexkohler** [lancedb/lance#2722]
Hey all, possible I'm misunderstanding something here, but Inoticed that writing datasets with `use_legacy_format=False` doesn't actually seem to be writing using the V2 version (according to `LanceDataset.data_storage_version`).

Lance version:  0.16.0

Repro:
```Python
dataset_url="/tmp"
table_name="test"
db = lancedb.connect(dataset_uri)
table = db.open_table(table_name)
...
table_uri = table._dataset_uri
lance.write_dataset(
    data,
    table_uri,
    schema=schema,
    mode="append",
    use_legacy_format=False,
)
ds = table.to_lance()
print(ds.data_storage_version) # Prints '0.1'
```

**Comment by alexkohler** [comment]
From what I can see, this also happens when using `data_storage_version="2.0"` instead of the deprecated `use_legacy_format` argument.

**Comment by westonpace** [comment]
A table can only have one data storage version and that is set when the table is first created.  It looks like you are opening an existing table?  Presumably one that is in the v1 format already?  Or it's possible I am misunderstanding.

Currently, there is no way to migrate the data storage version of existing tables (though we'd like to have that soon).  If you want to convert a table from one version to another you will need to create a new dataset and copy the data from the old one.

**Comment by alexkohler** [comment]
> A table can only have one data storage version and that is set when the table is first created. It looks like you are opening an existing table? Presumably one that is in the v1 format already? Or it's possible I am misunderstanding.

Ah, this was the issue - the table was created with the non-async APIs (and hence had a version of V1). Feel free to close this out, thanks for the quick response.

**Comment by wjones127** [comment]
> the only way to do that is directly through the raw lance APIs

The async APIs support this right now, but the sync ones don't currently:

https://lancedb.github.io/lancedb/guides/storage/#dynamodb-commit-store-for-concurrent-writes
