### ISSUE TITLE
The document mismatch with the code

### ISSUE THREAD

**Issue by jo3yzhu** [lancedb/lance#2733]
In the file transaction.rs, the comment illustrated that Delete conflicts with Append as below:
<img width="774" alt="image" src="https://github.com/user-attachments/assets/20d00a64-228d-4898-81f3-6d73067b756e">
While in the function ```conflicts_with``` Delete doesn't conflict with Append.
<img width="913" alt="image" src="https://github.com/user-attachments/assets/74f94794-a095-4568-8b9a-a0ed5f41df88">

**Comment by wjones127** [comment]
Ah, you are right. I forgot to update the docs in this PR where I relaxed the default isolation level:
https://github.com/lancedb/lance/pull/2537
