### ISSUE TITLE
IVF_PQ cosine vector index creation fails with 'Due to schema we expected a struct column..' despite schema not containing a struct column

### ISSUE THREAD

**Issue by alexkohler** [lancedb/lance#2758]
I have a V2 lance dataset with ~400m rows. I attempted to create a cosine vector index using the lancedb APIs with the following:
```Python
table.create_index(
	num_partitions=114794,  # ~4000 rows per parittion
	num_sub_vectors=64,
	accelerator="cuda"
	metric="cosine",
)
```

Dataset/version info (omitted actual field names, but I have 11 string fields, 1 uint64, 1 uint32, and 1 vector field)
```python
>>> print(lancedb.__version__)
0.12.0
>>> print(lance.__version__)
0.17.0

>>> print(len(table))
459173637
>>> ds = table.to_lance()
>>> ds.data_storage_version
'2.0'
>>> print(table.schema)
field1: string
field2: string
field3: string
field4: string
field5: uint64
field6: uint32
vector: fixed_size_list<item: float>[512]
  child 0, item: float
field7: string
field8: string
field9: string
field10: string
field11: string
field12: string
field13: string
```

My vector indexing seemed to reach the "sorted chunks" step and the nfailed with the following:
```
[2024-08-20T08:16:04Z INFO  lance_index::vector::ivf::shuffler] Writing partition 109000/114793
[2024-08-20T08:16:04Z INFO  lance_index::vector::ivf::shuffler] Writing partition 110000/114793
[2024-08-20T08:16:04Z INFO  lance_index::vector::ivf::shuffler] Writing partition 111000/114793
[2024-08-20T08:16:04Z INFO  lance_index::vector::ivf::shuffler] Writing partition 112000/114793
[2024-08-20T08:16:05Z INFO  lance_index::vector::ivf::shuffler] created sorted chunks in 508.575499256s
thread '<unnamed>' panicked at /root/lance/rust/lance-encoding/src/decoder.rs:810:82:
called `Result::unwrap()` on an `Err` value: InvalidInput { source: "Due to schema we expected a struct column but we received a column with 3 pages and right now we only support struct columns with 1 page", location: Location { file: "/root/lance/rust/lance-encoding/src/decoder.rs", line: 653, column: 251 } }
```

From what I can see, I don't actually have a struct column anywhere - any idea what's going wrong here?

**Comment by wjones127** [comment]
What exact version is this? We haven't even released Lance `0.17.0`, so not sure if this is a custom build or a pre-release. Need to know this exactly to narrow down the issue and reproduce.

**Comment by westonpace** [comment]
> I don't actually have a struct column anywhere - any idea what's going wrong here?

One of the intermediate index stages has a `List<Struct<...>>` schema (the output of the shuffle step) where each row is a partition (and has columns like "row id" and "pq vector")

**Comment by alexkohler** [comment]
> What exact version is this? We haven't even released Lance 0.17.0, so not sure if this is a custom build or a pre-release. Need to know this exactly to narrow down the issue and reproduce.

Ah, sorry, yes, this was built from main (SHA `711bad79a5492162ddfd71e7a2b39fce6ffc23a4`). Happy to retry this on a tagged release too see if it's reproducible. :+1:

**Comment by westonpace** [comment]
Huh...my suspicion was https://github.com/lancedb/lance/commit/7a36b28ab0a83d1240af0e8e055d845831abbd40 but 711bad wouldn't include that.

Also, `~4000 rows per parittion` is old advice.  We recommend these days to use `sqrt(# rows)` which would be more like 20k?  I haven't tested anything with 100k+ partitions (most I've tested with is 35k) so that might be a way to reproduce.

**Comment by westonpace** [comment]
I can reproduce this on `7a36b28ab0a83d1240af0e8e055d845831abbd40`.  Will dig in a bit and see what's going on.

**Comment by westonpace** [comment]
Confirmed smaller # partitions should avoid this.  The fix is also [here](https://github.com/lancedb/lance/pull/2762).

**Comment by alexkohler** [comment]
Awesome, thank you!

**Comment by alexkohler** [comment]
Using a smaller number of partitions also fixed my issue. Thanks again :+1:
