### ISSUE TITLE
Fedora 40 Rust compilation fails for lancedb and lance ?

### ISSUE THREAD

**Issue by johnjozwiakmodulus** [lancedb/lance#2774]
MacOS builds fine, but on Fedora 40 (arm) the trivial hello world single line program in Rust, if lance or lancedb is specified in Cargo.toml (and not even used), fails compilation with protoc complaints.

Is this a new or known issue?

cargo init lanceprotobufissue
cd lanceprotobufissue
cargo add lancedb
cargo build

**Comment by wjones127** [comment]
What version of `protoc` are you using?

**Comment by johnjozwiakmodulus** [comment]
libprotoc 3.19.6
lancedb = "0.9.0" in Cargo.toml (which is minimal...it's a one line hello world main.rs)

error: failed to run custom build command for `lance-encoding v0.16.0`

Caused by:
  process didn't exit successfully: `/home/johnjoz/vampiredom/lancedb_test/target/debug/build/lance-encoding-4b6cccdcf2d6df3b/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=protos

  --- stderr
  Error: Custom { kind: Other, error: "protoc failed: google/protobuf/empty.proto: File not found.\nencodings.proto:8:1: Import \"google/protobuf/empty.proto\" was not found or had errors.\nencodings.proto:249:5: \"google.protobuf.Empty\" is not defined.\n" }
warning: build failed, waiting for other jobs to finish...

**Comment by wjones127** [comment]
You likely just need a newer version of `protoc`

**Comment by johnjozwiakmodulus** [comment]
I looked and think it's the latest version.   can try a manual install.

**Comment by johnjozwiakmodulus** [comment]
will let you know.   thanks, too, of course.

**Comment by johnjozwiakmodulus** [comment]
Yes, thank you :  manual install of prebuilt platform binaries from the Google github repo resolved the issue and i'm back in business.   Will relay this to the Fedora package manager crew.
