### ISSUE TITLE
Map errors to correct `LanceError`

### ISSUE THREAD

**Issue by QianZhu** [lancedb/lance#2847]
Currently error codes are not correctly mapped. For example, all of the following are mapped with `LanceError(IO)` while they should be `BadRequest`:
https://github.com/lancedb/lance/blob/2838a87297213a38900606f2aab8d73534dd735c/rust/lance/src/dataset/scanner.rs#L281
https://github.com/lancedb/lance/blob/2838a87297213a38900606f2aab8d73534dd735c/rust/lance/src/dataset/scanner.rs#L372
https://github.com/lancedb/lance/blob/2838a87297213a38900606f2aab8d73534dd735c/rust/lance/src/dataset/scanner.rs#L471
https://github.com/lancedb/lance/blob/2838a87297213a38900606f2aab8d73534dd735c/rust/lance/src/dataset/scanner.rs#L478
https://github.com/lancedb/lance/blob/2838a87297213a38900606f2aab8d73534dd735c/rust/lance/src/dataset/scanner.rs#L498
https://github.com/lancedb/lance/blob/2838a87297213a38900606f2aab8d73534dd735c/rust/lance/src/dataset/scanner.rs#L501

Todo: map the errors to the corresponding `LanceError` types

**Comment by LuQQiu** [comment]
Addressed in https://github.com/lancedb/lance/pull/2845
