### ISSUE TITLE
LanceDB python example not working in python 3.10 (legacy file format)

### ISSUE THREAD

**Issue by bfcrampton** [lancedb/lance#2881]
I'm trying to profile LanceDB for my potential use case, but I'm hitting an error just doing the basic conversion and read of parquet files. Here are the steps to reproduce (following the [quick start](https://github.com/lancedb/lance#quick-start) guide):

```
$ pyenv virtualenv 3.10 test-lancedb
$ pyenv activate test-lancedb
$ pip install lancedb
$ python
import pyarrow as pa
import lance
input_uri = "gs://bucket-name/path/to/file.parquet"
output_uri = "gs://bucket-name/path/to/file.lance"
parquet = pa.dataset.dataset(input_uri, format='parquet')
lance.write_dataset(parquet, output_uri)

dataset = lance.dataset(output_uri)
df = dataset.to_table().to_pandas()
```

I get an error on the final line trying to read the lancedb dataset into a dataframe. Here is the error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jupyter/.local/lib/python3.9/site-packages/lance/dataset.py", line 480, in to_table
    return self.scanner(
  File "/home/jupyter/.local/lib/python3.9/site-packages/lance/dataset.py", line 2537, in to_table
    return self.to_reader().read_all()
  File "pyarrow/ipc.pxi", line 750, in pyarrow.lib.RecordBatchReader.read_all
  File "pyarrow/error.pxi", line 115, in pyarrow.lib.check_status
OSError: Io error: Execution error: LanceError(Arrow): Invalid argument error: column types must match schema types, expected List(Field { name: "element", data_type: Float64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }) but found List(Field { name: "item", data_type: Float64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }) at column index 10, /home/runner/work/lance/lance/rust/lance-file/src/reader.rs:443:12
```

I have tried this on both Linux and macOS, with the same result. I checked the schema of my originating parquet files (though I'm not sure why that would matter), and it seems to be using the newer `element` (vs. older `item`) Arrow format:
```
>>> parquet.schema
job_id: string
filename: string
...
features_1: list<element: double>
  child 0, element: double
features_2: list<element: double>
  child 0, element: double
-- schema metadata --
pandas: '{"index_columns": [], "column_indexes": [{"name": null, "field_n' + 1696
```

Am I missing something here, or is there a bug in the latest version with python?

**Comment by bfcrampton** [comment]
Note: I switched to writing with the `data_storage_version=stable`, instead of the default `legacy`, and that seemed to fix the issue.

```
lance.write_dataset(parquet, output_uri, data_storage_version='stable')
```

**Comment by westonpace** [comment]
Ah, yes, this is a repeating bug in the parquet / arrow world :laughing: :cry: 

List fields are represented in Arrow as a parent field (which has the offsets buffer) and a child field (which has the values).  Unfortunately, this child field has a name, which is a little bonkers.

The name of the child field is meaningless, but it still manages to break a lot of tools.  Parquet always calls the child field "element" and pyarrow/lance always call it "item".

The stable (v2) storage version tolerates this pretty well.  We don't store any name and, at read time, we call it whatever you want to call it.

**Comment by westonpace** [comment]
Since the stable version is going to be the default in the next release I'm not sure it's worth fixing in the legacy format.  You can workaround the issue if you need to use the legacy format (I think) by using `use_compliant_nested_type=False` when you write the parquet file (but I haven't tried this myself)

**Comment by bfcrampton** [comment]
Thank you for the quick response and explanation! That makes sense, and I think I'll be going with v2 storage regardless, for some of the performance improvements.

Closing this out as no need to fix due.
