### ISSUE TITLE
Merge a column from one dataset to another.

### ISSUE THREAD

**Issue by pablete** [lancedb/lance#2929]
Hello, I am having trouble merging 2 datasets since I always get OOM. 
The datasets are 11M rows with the source being"uid" and  "image bytes" (512x910) and the second dataset being "uid" and "vector (4,32,32)"

```python
ds_master = lance.dataset("...") ~700Gb
ds_vae    = lance.dataset("...") ~1.2Tb

# First attempt
ds_master.merge(ds_vae, left_on="uid")

# Second attempt
ds_iterator = ds_vae.to_batches()
ds_master.merge(ds_iterator, left_on="uid", schema=ds_vae.schema)

# Third attempt
rbr = pa.RecordBatchReader.from_batches(ds_vae.schema, ds_vae.to_batches())
ds_master.merge(rbr, left_on="uid", schema=ds_vae.schema)
```

My 3 attempt to join (or merge) these 2 columns have failed exhausting the memory of my node 768Gb. 

Am I doing something wrong? Is there a way to achieve the same operation, appending columns to a master dataset but without OOM? 

Thanks in advance

**Comment by pablete** [comment]
The main advantage of using lance was that I can process an focus a column at a time.

Is there another way to perform this join with less memory?

**Comment by wjones127** [comment]
It looks like you also posted in the Discord
/ channel and are getting answers there:

https://discord.com/channels/1030247538198061086/1105226910528716912/1288249286676451429

I'm going to close this and let you continue the conversation in Discord.

**Comment by thuyen** [comment]
Do we have document or example on how to do this? Thanks.

**Comment by westonpace** [comment]
Copying from the discord conversation.  The recommendation was to use `merge_insert` instead of `merge`.  The `merge` method will accumulate an entire fragments worth of data in memory which could lead to OOM.  The `merge_insert` method will operation on batches.

There was some later discussion about how that operation might be parallelized.  It didn't conclude.
