### ISSUE TITLE
Warning issued if limit is larger than num rows

### ISSUE THREAD

**Issue by wjones127** [lancedb/lance#3086]
When we do `head()`, we should check the number of rows in the table before performing take, and just use the lower value. That way we avoid this unnecessary warning.

https://github.com/lancedb/lance/blob/ceaf49c9d24eab6cf2dd61712849cb4f3bd14d69/rust/lance/src/dataset/scanner.rs#L1189C43-L1189C44

We actually seem to do this for offset, just not limit.

```python
import lance
import pyarrow as pa

data = pa.table({"x": [1, 2, 3]})
ds = lance.write_dataset(data, "./repro_limit")
ds.to_table(limit=10)
```
```
[2024-11-04T21:03:31Z WARN  lance::io::exec::scan] Ran out of fragments before we were done scanning for range: 0..10
pyarrow.Table
x: int64
----
x: [[1,2,3]]
```

Same with head:

```python
ds.head(10)
```
```
[2024-11-04T21:03:42Z WARN  lance::io::exec::scan] Ran out of fragments before we were done scanning for range: 0..10
pyarrow.Table
x: int64
----
x: [[1,2,3]]
```

**Comment by wjones127** [comment]
This came from https://github.com/lancedb/lance/pull/2747

**Comment by takaebato** [comment]
I'll work on this if no one else is!
