### ISSUE TITLE
Pylance shoud use a sub-level logger of logging

### ISSUE THREAD

**Issue by yanghua** [lancedb/lance#3195]
Currently, I noticed that PyLance directly uses logging to record logs. So, when we need to modify the log level, we have to do it in the following way:

```
logging.basicConfig(level=logging.DEBUG)
```

The intention behind this is to achieve the goal by modifying the root logger of logging. However, this doesn't seem to be an optimal practice. The optimal practice should be to use the sublevel of logging to prevent changes to the log level from having out-of-scope impacts, [like the fsspec's practice](https://github.com/fsspec/filesystem_spec/blob/master/fsspec/utils.py#L480). Generally, in a typical Python project, multiple frameworks are usually used, and they may all use the logging modules. If we modify the log level of the root logger, the impact scope of this change may exceed expectations (or there may be side effects).
Therefore, my suggestion is to use the sub-logger and make the following changes:

* Use `logging.getLogger()` to obtain pylance's logger;
* Use APIs or environment variables to control the log level of the PyLance logger.

**Comment by yanghua** [comment]
@westonpace @wjones127 WDYT?

**Comment by changhiskhan** [comment]
This makes sense to me. Would you have bandwidth to make a PR to migrate the logging? 

Also is it better to do getLogger() or getLogger(__name__)?

(Cc 
@wjones127 @westonpace if you guys have thoughts)

**Comment by yanghua** [comment]
>> Would you have bandwidth to make a PR to migrate the logging?

Yes, I will submit a PR to do this.

>> Also is it better to do getLogger() or getLogger(name)?

IMO, getLogger(name) is better
