### ISSUE TITLE
Is there a way to create a dataset/commit from written fragment file paths?

### ISSUE THREAD

**Issue by tonyf** [lancedb/lance#3265]
Hey guys, I'm working on fairly large datasets on the orders of 10m-1B rows. Currently, I'm using ray to process & write the dataset using the `LanceFragmentWriter` and the `LanceCommitter`. However, with these datasets, node failures and timeouts are an issue and I've been running up against the limits of lance's ability to be resilient against such failures. 

Currently, if my node dies/crashes in the middle of writing such a dataset, I'll have lots of fragments written to s3 but I have no way to resume from where I left off. 

Is there a way to create a commit from a list of fragment file paths?

**Comment by wjones127** [comment]
> Is there a way to create a commit from a list of fragment file paths?

Just knowing the file paths is not enough; there's other important metadata you need. Our APIs generally return a `FragmentMetadata` once they complete. You are expected to save those somewhere safe in order to be able to resume the job. They can either be pickled or serialized as JSON. Then you can wrap them in an operation and pass them to [LanceDataset.commit()](https://lancedb.github.io/lance/api/python/lance.html#lance.dataset.LanceDataset.commit)

Note that in Lance, each fragment can have multiple data files. So strictly speaking, we can't figure out the fragment structure just from a flat list of data files. To properly handle fragments, you should want to track that metadata instead.

**Comment by tonyf** [comment]
Yeah, that's what I figured. Would be nice if the ray integration handled this in some way. Or, if any of the ways to append rows did. Kinda like how checkpointing works for add_columns udfs

**Comment by tonyf** [comment]
Looks like Fragment exposes `.from_file` though?

```
@staticmethod
def create_from_file(
    filename: Union[str, Path],
    dataset: LanceDataset,
    fragment_id: int,
) -> FragmentMetadata:
    """Create a fragment from the given datafile uri.

    This can be used if the datafile is loss from dataset.

    .. warning::

        Internal API. This method is not intended to be used by end users.

    Parameters
    ----------
    filename: str
        The filename of the datafile.
    dataset: LanceDataset
        The dataset that the fragment belongs to.
    fragment_id: int
        The ID of the fragment.
    """
    fragment = _Fragment.create_from_file(filename, dataset._ds, fragment_id)
    return FragmentMetadata(fragment.json())
    ```
    
I feel like this could just read the fragment_id from the file itself at which point resumption would be possible

**Comment by wjones127** [comment]
@tonyf What kind of writes are you looking to do? Is it just appends?

**Comment by tonyf** [comment]
Just appends. I'm using the ray integration to convert datasets to lance as we've built up a lot of our model training infra around it. But I have to start from scratch every time there's a random failure.

**Comment by tonyf** [comment]
I was able to get this working with roughly the following script:

```
from s3fs import S3FileSystem
from concurrent.futures import ThreadPoolExecutor
from functools import partial

paths = fs.ls("s3://.../data")
fragment_paths = [p.replace(".../data/", "") for p in fragment_paths

uri = ...
schema = pa.schema([...])
dataset = lance.write_dataset([], uri, schema)

with ThreadPoolExecutor() as executor:
    fragments = list(exectuor.map(
        partial(LanceFragment.create_from_file, filename=item[1], dataset=dataset, fragment_id:item[0]), 
        enumerate(fragment_paths),
    ))

op = lance.LanceOperation.Append(fragments)
Lance.LanceDataset.commit(dataset, op, read_version=1)
```
