### ISSUE TITLE
[Rust] Partition Support

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lance#458]
# Problem Statement

After the new disk layout for multi-versioned dataset support, we need to bring back the partitioning support with the dataset. 

- [ ] Pyarrow `write_dataset()` api passes partition parameters.
- [ ] Rust organizes dataset in partitions (not necessary to be Hive partitioned, see Iceberg)
- [ ] Reader / Scanner can do partition pruning

**Comment by changhiskhan** [comment]
This is subsumed under #952
