### ISSUE TITLE
Dataset or TakeExec cache the opened fragment.

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lance#614]
# Problem Statement

When filter is provided, we will build an I/O execution plan like

```
LocalTakeExec() -> FilterExec() -> Scan()
```

To make the scan more efficient, the `LocalTakeExec` node should have maintain `FileReader` for the same file opened in Scan, so that `LakeTakeExec` node can do random access take without repeatedly open the same file.

In the previous C++ version, we had made the protocol between execution node to pass the batch id in `ScanBatch`

https://github.com/eto-ai/lance/blob/78e5af7dec1a9602823797ba18eafc632ba727c3/cpp/src/lance/io/exec/take.cc#L32

Which is challenging to implement in Rust and using Datafusion's physical execution plan.

# Desired Solution

When scanning a dataset with filter pushdown, `LocalTakeExec` does not need to repeatedly open new files.

**Comment by changhiskhan** [comment]
Decision was to do some more comprehensive benchmarking first and then we can re-open various optimization issues
