### ISSUE TITLE
Technical debt

### ISSUE THREAD

**Issue by arita37** [lancedb/lance#703]
My point is:

please separate your data archivage format
(Read/write engine)
With your analytics (ANN algo).

Data archivage format should be opened and use by anybody.

analytics becomes technical debt soon and unflexible.

**Comment by changhiskhan** [comment]
You're absolutely right. We've been thinking about how best to refactor this (e.g., https://github.com/eto-ai/lance/issues/687). Any interest in working with us to make that happen? would love to get more of your insights on this.

**Comment by changhiskhan** [comment]
Appreciate the feedback. We've done some of these. If there's anything else specific, happy to discuss in new github issues.
