### ISSUE TITLE
Error reading data with Lance

### ISSUE THREAD

**Issue by lucazanna** [lancedb/lance#715]
I am trying out Lance and somehow I am not able to read Lance data.

Here is what I tried to do:

```
import lance

import pyarrow as pa
import pyarrow.dataset

dataset = pa.dataset.dataset('data_clean.parquet', format='parquet')

# side question for the write dataset: is there a way to configure it to overwrite data? 
# to avoid error messages if I launch it multiple times
lance.write_dataset(dataset, "data_clean.lance") 

dataset_lance = lance.dataset("data_clean.lance")

dataset_lance.head(5)
# This returns
# ArrowInvalid: C Data interface error: Io error: Execution error: LanceError(Arrow): Invalid argument error: Value at position 0 out of bounds: 0 (should be in [0, -1])
```

Would you know what can be the reason for this? 
Look forward to trying out Lance

I'm on Python 3.11 with Lance version 0.3.16 and Pyarrow version 11.0.0

**Comment by changhiskhan** [comment]
thanks for the bug report. would you mind sharing the schema? 

>> is there a way to configure it to overwrite data? 
If you supply it with `mode="overwrite"` it'll create a new snapshot version that overwrites the existing version (the old data is kept but not "visible" to the latest version)

**Comment by lucazanna** [comment]
[data_clean.zip](https://github.com/eto-ai/lance/files/11029246/data_clean.zip)

Of course, here is the schema:
InvoiceNo: dictionary<values=string, indices=int32, ordered=0>
StockCode: dictionary<values=string, indices=int32, ordered=0>
Description: dictionary<values=string, indices=int32, ordered=0>
Quantity: int64
InvoiceDate: date32[day]
UnitPrice: double
CustomerID: dictionary<values=string, indices=int32, ordered=0>
Country: dictionary<values=string, indices=int32, ordered=0>
Sales: double

I am also attaching the file, in case that helps. It's a public dataset

**Comment by lucazanna** [comment]
thank you.

If I understand, you do something similar to Delta Lake for tracking different versions of the file?
