### ISSUE TITLE
Segfaults even with duckdb v0.7+ installed

### ISSUE THREAD

**Issue by jrabary** [lancedb/lance#717]
Hi,
I'm giving lance a try and get segfaults even with duckedb v0.7.1. I'm using Mac OS with m1 chips.
Any ideas ?

**Comment by jrabary** [comment]
I've just find out why I get this. I have a large parquet file with binary image inside. Generated from coco dataset. When I run a query with `duckdb.query("SELECT * ...")` I get a segfault. But if I specify a column like `"SELECT image ..."` it works.

**Comment by changhiskhan** [comment]
Would you be able to share the data? 
1. If you do "SELECT * EXCLUDE(image) ...", do you still get a segfault? If so, can you share the parquet dataset without the image column (hopefully making it much smaller) ?
2. OR if like the first 10 rows still reproduces the error, just share the first 10 rows?

Another possibility is that we're working on https://github.com/eto-ai/lance/pull/664 which adds support for list-of-dict or list-of-struct-with-dict fields. If you've converted data from parquet, it's possible this is the problem too.

If you can, please share the data so we can verify it from our end before the next release
