### ISSUE TITLE
Add support for directly lance datasets as input to lance.write_dataset

### ISSUE THREAD

**Issue by gsilvestrin** [lancedb/lance#736]
When writing a dataset previously loaded by `lance.dataset`, the process segfaults. The workaround is to convert a dataset to a table before writing it.

This sample python code triggers the segfault

```python
import lance

import pandas as pd
import pyarrow as pa
import pyarrow.dataset

df = pd.DataFrame({"a": [5], "b": [10]})
uri = "/tmp/test.parquet"
tbl = pa.Table.from_pandas(df)
pa.dataset.write_dataset(tbl, uri, format='parquet')

parquet = pa.dataset.dataset(uri, format='parquet')
lance.write_dataset(parquet, "/tmp/test.lance")

dataset = lance.dataset("/tmp/test.lance")
assert isinstance(dataset, pa.dataset.Dataset)

lance.write_dataset(dataset, "/tmp/test.lance")
```

**Comment by changhiskhan** [comment]
Currently, the pyo3 code for writing a dataset requires a block_on call using tokio runtime. If the input dataset is also a LanceDataset, then the reading also requires a block_on call. This causes tokio to not be happy.

Instead the solution should be that the pyo3 interface should be converted to async and the blocking happens in python to convert to Table or write a dataset

**Comment by wjones127** [comment]
FYI the segfault from GC's repro actually has to do with this line:

https://github.com/lancedb/lance/blob/b974900b78a02a9b67580db637dba928a1c2f070/python/python/lance/dataset.py#L1015-L1016

Passing a `LanceDataset` to `pa.dataset.Scanner.from_dataset()` isn't safe.
