### ISSUE TITLE
Implement DiskANN 

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lance#745]
- [x] Build vamana graph in memory.
- [x] Benchmark graph construction performance
- [x] Benchmark recall on vamana graph
- [x] On-disk layout design.
- [ ] Integrate with the `dataset::create_index`
- [ ] Python API.
- [ ] `lq` CLI integration.

**Comment by changhiskhan** [comment]
the feature is largely code complete but is not optimized yet
