### ISSUE TITLE
Performance a sanity check over column name when writing new data.

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lance#839]
# Problem Statement

Users wrote dataset with columns such as "foo-bar" as column names into Lance Dataset. However, it prevents users to filter over the column , because sqlparser will treat it as `foo minus bar`. 

# Solution

Either we ban the column names with these characters, or change the sql-parser to allow users to use double / single quote to refer a column.

**Comment by jaichopra** [comment]
depending on what design we go for, a more interpretable error message to guide the user is needed
i'm a bit confused at the moment what the bug is if i use a keyword as a column name (which you're likely to hit as they are common)

**Comment by wjones127** [comment]
Well by default, sql-parser allows `"` to wrap column names. However, in https://github.com/lancedb/lance/pull/639/files we started parsing double quotes as strings (in SQL usually it's just single quotes). So I guess we can choose a different symbol. Maybe backtick, like MySQL?
