### ISSUE TITLE
[Rust] Change the version filename to be zero-padding numbers for better cloud storage scan performance

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lance#894]
# Problem Statement

We should name a version file as zero-padding "000000N.manifest". Because popular cloud storage keys are stored, It is cheaper to check out a manifest (snapshot) and scan the directory for any following logs after the snapshot version. 

# Requirements

We need to make the change to backward compatible.

**Comment by wjones127** [comment]
Superseded by #1362
