### ISSUE TITLE
Make duckdb and pandas optional dependencies

### ISSUE THREAD

**Issue by jaichopra** [lancedb/lance#901]
Currently DuckDB and pandas are required package dependency for Lance python (pylance)

They should only be an optional dependency

**Comment by eddyxu** [comment]
We still have a few places that use pandas

https://github.com/lancedb/lance/blob/main/python/python/lance/util.py#L19
https://github.com/lancedb/lance/blob/fdb56eb31154c52f74a80520902c86981f1ebff3/python/python/lance/dataset.py#L26

**Comment by eddyxu** [comment]
Close this for now. Pandas is hard to get rid of at the moment.
