### ISSUE TITLE
First pass at deletion support

### ISSUE THREAD

**Issue by wjones127** [lancedb/lance#908]
* [ ] Add field to Fragment for deletion id and type.
* [ ] Temporarily make code paths error when these aren't none
* [ ] Also implement array / bitmap write utilities:

```rust
enum DeletionFileType {
   Array,
   Bitmap,
}
struct DeletionFile {
    id: UUID,
    type: DeletionFileType,
}
fn write_bitmap(removed_rows: BooleanArray) -> Result<DeletionFile> {
}
```

**Comment by eddyxu** [comment]
Can delete id to be a var-length integer? it is smaller for one thing, on the other hand, it makes the deletion filepath more recognizable for "versions". 

DeletionFileType will be decided by % of true in the removed_rows?

**Comment by wjones127** [comment]
> Can delete id to be a var-length integer? it is smaller for one thing, on the other hand, it makes the deletion filepath more recognizable for "versions".

The UUID is to prevent collisions, for eventual concurrent writer support. We don't support concurrent writers yet, but I think we should try to plan to if we can. We could use an integer, but then how do we prevent collisions (a different writer overwrites our delete file)?

If the concern is easy debugging, we could make a more interpretable id by using a tuple of `(<read table version>: i64, <random int>: i32)`. Read table version being the version of the table the delete was operating on, which is most cases will be one less than the new table version. One possible generator for the random bits is a checksum algorithm, which has the added bonus of giving us a way to verify table integrity. To summarize, the filename would be:

```
{fragment_id}-{read_table_version_id}-{checksum}.bin
```

And the struct would be

```rust
struct DeletionFile {
    read_version: i64,
    checksum: i64,
    type: DeletionFileType,
}
```

What do you think of that?

**Comment by wjones127** [comment]
> DeletionFileType will be decided by % of true in the removed_rows?

Either than or some constant value (e.g. 1000). I think we can label that configuration unstable and decide which is a better parametrization when benchmarking. But percentage might be a better place to start.

**Comment by eddyxu** [comment]
> The UUID is to prevent collisions, for eventual concurrent writer support. 

It is fair, so in a case of multi-writers deletion, say two deletions from "vesion0" to version1 and version 2 in parallel. How do we know how to merge them together later, and at what time?

**Comment by eddyxu** [comment]
> > DeletionFileType will be decided by % of true in the removed_rows?
> 
> Either than or some constant value (e.g. 1000). I think we can label that configuration unstable and decide which is a better parametrization when benchmarking. But percentage might be a better place to start.

Ok, sounds good either way.

**Comment by wjones127** [comment]
> It is fair, so in a case of multi-writers deletion, say two deletions from "vesion0" to version1 and version 2 in parallel. How do we know how to merge them together later, and at what time?

If there's two concurrent deletes, I think we'll have to say one of them fails when it tries to commit its manifest file. It would just say "Error: a concurrent query has already deleted that data. Please try again." We might be able to implement retries in our library.

**Comment by wjones127** [comment]
> Checksum sounds expensive at the moment. As long as we have a forward-compatible way to present these fields, i am ok to leave them out for now.

We can make them optional; if turned of a generic i64 can be randomly generated. Each delete file should be small though, so I don't think the checksum would take that much time.

**Comment by eddyxu** [comment]
> > It is fair, so in a case of multi-writers deletion, say two deletions from "vesion0" to version1 and version 2 in parallel. How do we know how to merge them together later, and at what time?
> 
> If there's two concurrent deletes, I think we'll have to say one of them fails when it tries to commit its manifest file. It would just say "Error: a concurrent query has already deleted that data. Please try again." We might be able to implement retries in our library.

But if you fail a deletion, the deleted file should be be materialized on disk. Maybe I missed some design here.

**Comment by wjones127** [comment]
The sequence I'm thinking of is when you have two writers trying to delete parts of the same fragment. The sequence goes:

**writer 1**: Writes  `_deletions/1-10-abcd.bin`
**writer 2**: Writes `_deletions/1-10-dbef.bin`
**writer 1**: Writes `_versions/11.manifest`
**writer 2**: Tries to write `_versions/11.manifest`, but fails because it already exists.
**writer 2**: Initiates retry: writes `_deletions/1-11-asdf.bin` (now reading the new version 11)
**writer 2**: Writes `_versions/12.manifest`
**writer 2**: Deletes `_deletions/1-10-dbef.bin` (cleanup uncommitted file)

**Comment by eddyxu** [comment]
How does it work distributedly, say , we first ship "deletion op" to each worker, apply deletion there, and gather a bunch of new `Fragment` object back with the deletion field, and try to commit it?  The retry will result to "reschedule deletion tasks" again?

Curious how delta lake/iceberg handle it.

**Comment by wjones127** [comment]
> How does it work distributedly, say , we first ship "deletion op" to each worker, apply deletion there, and gather a bunch of new Fragment object back with the deletion field, and try to commit it? The retry will result to "reschedule deletion tasks" again?

Yes, that's how Delta Lake handles it. The driver node is responsible for committing the final manifest, and creating retry jobs if necessary.

**Comment by eddyxu** [comment]
Got it. Does deltalake "cleanup" the failed commit? I kind of lean to just leave them there and let GC / VACCUM to handle it later. Curious whether Deltalake has some different considerations.

**Comment by wjones127** [comment]
TBH I think they just VACUUM most of the time. It's also there in case a cluster crashes mid-write. But I figure if an operation has time to cleanup, it's nice to do, even if it's not required.
