### ISSUE TITLE
How to create large dataset that doesn't fit into memory

### ISSUE THREAD

**Issue by jrabary** [lancedb/lance#923]
Is there any documentation on how to create large dataset (videos and images for computer vision application) that don't fit into memory ? How to handle file split automatically ?

**Comment by wjones127** [comment]
Hi @jrabary, this is described in our docs under [Read and Write Lance Dataset](https://lancedb.github.io/lance/read_and_write.html#writing-lance-dataset)

Our method `write_dataset()` can take an iterator of `RecordBatch`, which is shown in the example I linked. It can also take a `RecordBatchReader`, which is returned by some APIs in PyArrow as well as by DuckDB. In DuckDB, you can use `.fetch_record_batch()` to get a `RecordBatchReader` that will stream its results to Lance.

To control how files are split, there is an argument `max_rows_per_file`. Once the max rows is hit, Lance will finish the current file and start a new file.
