### ISSUE TITLE
Add a rmdir() function to ObjectStore

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lance#932]
# Problem Statement

We need to have a `rmdir()` function to easily delete a directory recursively, for background compaction and data management.

**Comment by wjones127** [comment]
We recently added a method in object store called `delete_stream`, which deletes a stream of paths in, using batch APIs where available (currently only S3) and making requests in parallel.  You can pipe the output of listing into that to remove a directory in object stores.

https://github.com/apache/arrow-rs/blob/dde65391263039f1431df9eca6a429de0b9457b3/object_store/src/lib.rs#L1593-L1603
