### ISSUE TITLE
Polars

### ISSUE THREAD

**Issue by jordan-carson** [lancedb/lance#936]
The docs mention lance supports polars. Is this feature available in the latest release for python? 

Thanks
jordan

**Comment by wjones127** [comment]
Lance and Polars are both use Arrow as their in-memory format, so they can exchange data very efficiently.

So for example, you can write a Polars DataFrame by calling `.to_arrow()` first:

```python
import lance
import polars as pl
from datetime import datetime

df = pl.DataFrame(
    {
        "integer": [1, 2, 3, 4, 5],
        "date": [
            datetime(2022, 1, 1),
            datetime(2022, 1, 2),
            datetime(2022, 1, 3),
            datetime(2022, 1, 4),
            datetime(2022, 1, 5),
        ],
        "float": [4.0, 5.0, 6.0, 7.0, 8.0],
    }
)

lance.write_dataset(df.to_arrow(), "test_dataset")
```

Then you can load a Lance dataset and create a lazy Polars query on top with `scan_pyarrow_dataset`:

```python
ds = lance.dataset("test_dataset")
(
    pl.scan_pyarrow_dataset(ds)
    .filter(pl.col("integer") > 2)
    .select(["date", "float"])
    .collect()
)
```

This allows you to write queries in Polars, but predicates and column selection will be pushed down into Lance.

**Comment by jordan-carson** [comment]
Simple. Thanks @wjones127
