### ISSUE TITLE
Support creating an empty table

### ISSUE THREAD

**Issue by wjones127** [lancedb/lance#954]

**Comment by tarunsamanta2k20** [comment]
I'd like to look into this.

**Comment by trueutkarsh** [comment]
Hi @wjones127  ,
I am trying to understand this issue in a bit more depth. What would be the schema for an empty table ? We could use the empty schema but my understanding is we would override it when we see an overwrite or append operation on the dataset. 
Or schema **must** be provided when the content is empty.
Please let me know if this interpretation and scope of the issue correct ?
Thanks
