### ISSUE TITLE
Put `OPQ` module after a feature flag, so that by default we dont need to build openblas

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lance#985]
# Problem Statement

Only the opq module uses `blas` now, and it causes significant difficulty for us to maintain windows build.

# Desired Behavior

Make `opq` an optional feature, so most of the users dont need to build `openblas` by default:

Dependencies that can make optional in this process:

* `cblas`
* `lapack`
* `openblas-src`
* `acclerate-src`

**Comment by dnsco** [comment]
Thank you :partyparrot:
